### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'clip'

### ISSUE THREAD

**Issue by Dawn-LX** [mrwu-mac/EoID#2]
Hello, Can you fix this ?
```
Traceback (most recent call last):
  File "main.py", line 356, in <module>
    main(args)
  File "main.py", line 262, in main
    device, args)
  File "/home/gkf/anaconda3/envs/torch17cu110/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/home/gkf/project/EoID/engine.py", line 107, in evaluate_hoi
    if args.clip == 6:
AttributeError: 'Namespace' object has no attribute 'clip'
```

And I did not find definition of `args.clip` in main.py

**Comment by mrwu-mac** [comment]
Thank you for pointing out the problem. The problem has been fixed.
